
version: '3'
services:
  mysqldb:
    image: mysql
    container_name: mysql-container
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: carinsurance
      MYSQL_USER: user
      MYSQL_PASSWORD: password
    ports:
      - 4444:3306


